import { can, canSeeSchool, type AppModule } from "./access-control";
import { adminDb, resolveAccess } from "./app-access.server";
import { resolveSupabaseServerConfig } from "./supabase-config.server";
import { createAdminFetch } from "./supabase-admin.server";

const modules: Record<string, AppModule> = {
  schools: "schools",
  students: "students",
  attendance: "attendance",
  school_divisions: "schools",
  school_clusters: "schools",
};
export type DataRequest = {
  token: string;
  table: string;
  query: string;
  method: string;
  body?: string;
  headers: Record<string, string>;
};
export async function privateData(request: DataRequest) {
  const profile = await resolveAccess(request.token);
  const module = modules[request.table];
  if (!module || !Object.hasOwn(modules, request.table)) throw new Error("Unsupported data table");
  const action = (
    { GET: "view", HEAD: "view", POST: "add", PATCH: "edit", DELETE: "delete" } as const
  )[request.method as "GET"];
  if (!action) throw new Error("Unsupported operation");
  // School/student lookups support the modules that already display these records.
  const readModules: AppModule[] =
    request.table === "schools" ||
    request.table === "school_clusters" ||
    request.table === "school_divisions"
      ? [
          "schools",
          "dashboard",
          "students",
          "attendance",
          "assessments",
          "clicker",
          "exam_report",
          "session_status",
        ]
      : request.table === "students"
        ? ["students", "attendance", "clicker", "exam_report"]
        : ["attendance", "exam_report"];
  if (
    !(action === "view"
      ? readModules.some((m) => can(profile, m, "view"))
      : can(profile, module, action))
  )
    throw new Error("Permission denied");
  const params = new URLSearchParams(request.query);
  // Never allow embedded relations to read account tables through a join.
  const select = params.get("select");
  if (params.getAll("select").length > 1) throw new Error("Unsupported selection");
  if (
    select &&
    !(request.table === "schools" && select === "*,students(count)") &&
    !/^(\*|[a-z_][a-z_0-9]*(\s*,\s*[a-z_][a-z_0-9]*)*)$/.test(select)
  )
    throw new Error("Unsupported selection");
  for (const key of params.keys()) {
    if (!/^[a-z_][a-z_0-9]*$/.test(key)) throw new Error("Unsupported filter");
  }
  const scoped = profile.role !== "admin" && !profile.allSchools;
  const scopeColumn = request.table === "schools" ? "id" : "school_id";
  if (scoped && request.table !== "school_clusters") {
    const ids = profile.schoolIds.filter((id) => /^[0-9a-f-]{36}$/i.test(id));
    params.append(
      scopeColumn,
      `in.(${ids.length ? ids.join(",") : "00000000-0000-0000-0000-000000000000"})`,
    );
  }
  const headers = new Headers();
  for (const [key, value] of Object.entries(request.headers))
    if (["accept", "prefer", "range", "range-unit", "content-type"].includes(key.toLowerCase()))
      headers.set(key, value);
  const upsert = headers.get("prefer")?.includes("resolution=") === true;
  if (upsert && !can(profile, module, "edit"))
    throw new Error("Edit permission is required for upserts");
  if (request.method === "POST" || request.method === "PATCH") {
    const body: unknown = JSON.parse(request.body ?? "{}");
    const rows = Array.isArray(body) ? body : [body];
    if (
      !rows.length ||
      rows.length > 1000 ||
      rows.some((row) => !row || typeof row !== "object" || Array.isArray(row))
    )
      throw new Error("Invalid records");
    for (const row of rows) {
      if (request.method === "PATCH" && Object.hasOwn(row, "id"))
        throw new Error("Record IDs cannot be changed");
      if (scoped) {
        if (
          request.table === "school_clusters" ||
          (request.table === "schools" && request.method === "POST")
        )
          throw new Error("Administrator approval required");
        if (
          (request.method === "POST" || row.school_id !== undefined) &&
          !canSeeSchool(profile, String(row.school_id ?? ""))
        )
          throw new Error("School access denied");
        if (upsert && request.table !== "attendance")
          throw new Error("Use edit to update existing records in your assigned schools");
        // A supplied primary key must never move an existing record into this user's scope.
        if (request.method === "POST" && row.id)
          throw new Error("New record IDs are generated by the server");
      }
    }
    if (request.table === "attendance") {
      const db = await adminDb();
      for (const row of rows) {
        if (
          request.method === "PATCH" &&
          (row.student_id !== undefined || row.school_id !== undefined)
        )
          throw new Error("Attendance assignments cannot be changed");
        if (request.method === "POST") {
          const { data, error } = await db
            .from("students")
            .select("school_id")
            .eq("id", row.student_id)
            .maybeSingle();
          if (
            error ||
            !data ||
            data.school_id !== row.school_id ||
            !canSeeSchool(profile, data.school_id)
          )
            throw new Error("Student school does not match");
        }
      }
    }
  }
  if (
    (request.method === "DELETE" || request.method === "PATCH") &&
    ![...new URLSearchParams(request.query).keys()].some(
      (k) => !["select", "order", "limit", "offset"].includes(k),
    )
  )
    throw new Error("Select records before changing them");
  const config = resolveSupabaseServerConfig(process.env);
  headers.set("apikey", config.key);
  headers.set("Authorization", `Bearer ${config.key}`);
  const response = await createAdminFetch(config.key)(
    `${config.url.replace(/\/$/, "")}/rest/v1/${request.table}?${params}`,
    {
      method: request.method,
      headers,
      body: request.body,
      signal: AbortSignal.timeout(60000),
    },
  );
  return {
    status: response.status,
    body: await response.text(),
    headers: {
      "content-type": response.headers.get("content-type") ?? "application/json",
      "content-range": response.headers.get("content-range") ?? "*/*",
    },
  };
}
