/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamReportIndexRouteImport } from './routes/exam-report.index'
import { Route as SchoolsSchoolIdRouteImport } from './routes/schools.$schoolId'
import { Route as ExamReportSchoolIdIndexRouteImport } from './routes/exam-report.$schoolId.index'
import { Route as ExamReportSchoolIdStudentsRouteImport } from './routes/exam-report.$schoolId.students'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamReportIndexRoute = ExamReportIndexRouteImport.update({
  id: '/exam-report/',
  path: '/exam-report/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsSchoolIdRoute = SchoolsSchoolIdRouteImport.update({
  id: '/schools/$schoolId',
  path: '/schools/$schoolId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamReportSchoolIdIndexRoute = ExamReportSchoolIdIndexRouteImport.update({
  id: '/exam-report/$schoolId/',
  path: '/exam-report/$schoolId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamReportSchoolIdStudentsRoute =
  ExamReportSchoolIdStudentsRouteImport.update({
    id: '/exam-report/$schoolId/students',
    path: '/exam-report/$schoolId/students',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/exam-report/': typeof ExamReportIndexRoute
  '/exam-report/$schoolId/students': typeof ExamReportSchoolIdStudentsRoute
  '/exam-report/$schoolId/': typeof ExamReportSchoolIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/exam-report': typeof ExamReportIndexRoute
  '/exam-report/$schoolId/students': typeof ExamReportSchoolIdStudentsRoute
  '/exam-report/$schoolId': typeof ExamReportSchoolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/schools/$schoolId': typeof SchoolsSchoolIdRoute
  '/exam-report/': typeof ExamReportIndexRoute
  '/exam-report/$schoolId/students': typeof ExamReportSchoolIdStudentsRoute
  '/exam-report/$schoolId/': typeof ExamReportSchoolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/schools/$schoolId'
    | '/exam-report/'
    | '/exam-report/$schoolId/students'
    | '/exam-report/$schoolId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/schools/$schoolId'
    | '/exam-report'
    | '/exam-report/$schoolId/students'
    | '/exam-report/$schoolId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/schools/$schoolId'
    | '/exam-report/'
    | '/exam-report/$schoolId/students'
    | '/exam-report/$schoolId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  SchoolsSchoolIdRoute: typeof SchoolsSchoolIdRoute
  ExamReportIndexRoute: typeof ExamReportIndexRoute
  ExamReportSchoolIdStudentsRoute: typeof ExamReportSchoolIdStudentsRoute
  ExamReportSchoolIdIndexRoute: typeof ExamReportSchoolIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-report/': {
      id: '/exam-report/'
      path: '/exam-report'
      fullPath: '/exam-report/'
      preLoaderRoute: typeof ExamReportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools/$schoolId': {
      id: '/schools/$schoolId'
      path: '/schools/$schoolId'
      fullPath: '/schools/$schoolId'
      preLoaderRoute: typeof SchoolsSchoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-report/$schoolId/': {
      id: '/exam-report/$schoolId/'
      path: '/exam-report/$schoolId'
      fullPath: '/exam-report/$schoolId/'
      preLoaderRoute: typeof ExamReportSchoolIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam-report/$schoolId/students': {
      id: '/exam-report/$schoolId/students'
      path: '/exam-report/$schoolId/students'
      fullPath: '/exam-report/$schoolId/students'
      preLoaderRoute: typeof ExamReportSchoolIdStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  SchoolsSchoolIdRoute: SchoolsSchoolIdRoute,
  ExamReportIndexRoute: ExamReportIndexRoute,
  ExamReportSchoolIdStudentsRoute: ExamReportSchoolIdStudentsRoute,
  ExamReportSchoolIdIndexRoute: ExamReportSchoolIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
